version: "3.8"

services:
    api:
        build:
            context: ./app
            dockerfile: ./docker/Dockerfile
        ports:
            - 8080:8080
        environment:
            - DB_URL=mongodb://db/myTestDB

            - MINIO_URL=minio.kevin-nguyen.tk
            - MINIO_ACCESS_KEY=admin
            - MINIO_SECRET_KEY=K6r3NPLK.ER'+Ezo
            - MINIO_BUCKET=ucar-testing

        volumes:
            - ./app:/app
    db:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./mongodb:/data/db
    # fe:
    #     build: 
    #         context: ./fe_app
    #         dockerfile: ./docker/Dockerfile
    #     ports:
    #         - 4200:4200
    #     volumes:
    #         - ./fe_app:/app
